---

- name: Nomad service options file
  template:
    src: "etc/nomad-daemon-options.j2"
    dest: "/etc/{{nomad_daemon_options_dirname}}/nomad"
    owner: "{{nomad_user}}"
    group: "{{nomad_group}}"
    mode: "0644"
  notify: nomad restart
  when: ansible_service_mgr != "systemd"

- name: Nomad Configuration
  template:
    src: etc/nomad.d/config.hcl.j2
    dest: "{{nomad_config_dir}}/{{item.key}}.hcl"
    owner: "{{nomad_user}}"
    group: "{{nomad_group}}"
    mode: "0644"
    #validate: "{{nomad_bin}} configtest -config-file {{nomad_config_dir}}/%s"
  with_dict: "{{nomad_config}}"
  notify: nomad restart

# vi:ts=2:sw=2:et:ft=yaml
